version: "3.4"
services:
  app:
    image: trycanonic/canonic
    platform: linux/x86_64
    volumes:
      - mongodbdata:/data/db
      - candata:/projects
      - dynamodb:/dynamodb
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "9191:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    depends_on:
      - watchtower

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=YOUR-EMAIL

  mongo:
    image: mongo
    restart: always
    container_name: canonic-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodbdata:
  candata:
  dynamodb:
  certs:
  vhost:
  html:
  acme:
